runner:

  # e.g.: https://github.com
  baseUrl: ""

  # e.g.: btungut
  organizationName: ""


  # Runner name which will be displayed on GitHub, defaults to hostname
  name: ""


  # Runner group name which will be displayed on GitHub, defaults to "Default"
  group: "Default"


  # GitHub runner labels to be used for runner selection in 'runs-on' section of workflow
  labels:
    - "dockerized-ubuntu"
    - "dockerized-ubuntu-20.04"
    - "dockerized-runner"
    # - "{{ .Release.Name }}"

  # --- AUTH ---
  # 1st option : PAT for generating GitHub runner tokens as plain text
  pat: ""
  # 2nd option : PAT for generating GitHub runner tokens as stored in Kubernetes secret
  patSecretName: ""
  patSecretKey: ""

nameOverride: ""
fullnameOverride: ""

revisionHistoryLimit: 0
replicaCount: 1

image:
  repository: btungut/github-runner-on-kubernetes
  pullPolicy: IfNotPresent
  tag: 2.311.1 #fea6bb5

imagePullSecrets: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10000
  runAsGroup: 10000

podAnnotations: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
