apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runner.fullname" . }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 0 }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runner.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: runner
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository | required "image.repository" }}:{{ .Values.image.tag | required "image.tag" }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GITHUB_URL
              value: {{ .Values.runner.baseUrl | required "runner.baseUrl" }}/{{ .Values.runner.organizationName | required "runner.organizationName" }}
            - name: GITHUB_ORG_NAME
              value: {{ .Values.runner.organizationName | required "runner.organizationName" }}
            {{- if .Values.runner.name }}
            - name: GITHUB_RUNNER_NAME
              value: {{ .Values.runner.name }}
            {{- end }}
            - name: GITHUB_RUNNER_GROUP
              value: {{ .Values.runner.group | required "runner.group" }}
            {{- if .Values.runner.labels }}
            - name: GITHUB_RUNNER_LABELS
              value: {{ tpl (.Values.runner.labels | join "," | trim | quote) . }}
            {{- end }}
            - name: GITHUB_PAT
            {{- if .Values.runner.patSecretName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.runner.patSecretName }}
                  key: {{ .Values.runner.patSecretKey | required "runner.patSecretKey must be provided" }}
            {{- else if .Values.runner.pat }}
              value: {{ .Values.runner.pat | trim | quote }}
            {{- else }}
            {{- fail "runner.pat or runner.patSecretName must be provided" }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}